### ISSUE TITLE
Creating CloudRunJob Block Error -> TypeError: Object of type 'SecretDict' is not JSON serializable

### ISSUE THREAD

**Issue by japerry911** [PrefectHQ/prefect-gcp#102]
Hello, 

I have been using [this blogpost](https://medium.com/the-prefect-blog/gcp-and-prefect-cloud-from-docker-container-to-cloud-vm-on-google-compute-engine-2dffa026d16b) as a walkthrough for setting up Prefect Agent with Compute Engine, and flows with Cloud Run Job Block.

Unfortunately, I am running into issues with the GCP Credentials block I think. 

Specifically I am receiving this error when I save a Cloud Run Job **block**:

```
File "pydantic/main.py", line 505, in pydantic.main.BaseModel.json
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/json/encoder.py", line [199](https://github.com/japerry911/crypto-data-pipeline/actions/runs/3834160612/jobs/6526312987#step:8:205), in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic/json.py", line 90, in pydantic.json.pydantic_encoder
TypeError: Object of type 'SecretDict' is not JSON serializable
Error: Process completed with exit code 1.
```

I have the following dependencies in my Poetry `pyproject.toml`, any idea if I am missing anything, or is this a bug within `Prefect-GCP`?:

```
[tool.poetry.dependencies]
python = "~3.10"
prefect-gcp = "^0.2.2"
google-cloud-storage = "^2.7.0"
google-cloud-bigquery = "^3.4.1"
google-auth-oauthlib = "^0.8.0"
google-auth = "^2.15.0"
pydata-google-auth = "^1.4.0"
```

Whatever it is, is there any way I could help address this if it's not an error on my end?

Thanks team.

**Comment by japerry911** [comment]
Here are the full logs:


```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
An exception occurred.
    return fn(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 230, in coroutine_wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 181, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/prefect/cli/deployment.py", line 930, in build
    deployment = await Deployment.build_from_flow(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/prefect/deployments.py", line 734, in build_from_flow
    await deployment.to_yaml(output)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/prefect/deployments.py", line 312, in to_yaml
    yaml_dict = self._yaml_dict()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/prefect/deployments.py", line 343, in _yaml_dict
    self.json(
  File "pydantic/main.py", line 505, in pydantic.main.BaseModel.json
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/json/encoder.py", line [199](https://github.com/japerry911/crypto-data-pipeline/actions/runs/3834160612/jobs/6526312987#step:8:205), in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic/json.py", line 90, in pydantic.json.pydantic_encoder
TypeError: Object of type 'SecretDict' is not JSON serializable
```

**Comment by ahuang11** [comment]
Thanks for reporting this. I couldn't seem to replicate with:
```
from prefect_gcp import GcpCredentials
from prefect_gcp.cloud_run import CloudRunJob
CloudRunJob(image="myimage", region="region", credentials=GcpCredentials.load("gcp-credentials")).save("testingissue")
```

Would you be able to run `pip install -U prefect` and `prefect block register -m prefect_gcp`?

**Comment by japerry911** [comment]
Hello!

Thank you for a prompt response. I'll dive into this in a few hours, I'll implement your recommendations and then try some things.

Thank you!

**Comment by japerry911** [comment]
@ahuang11 , I am sorry, I really was incorrect. 

I am actually receiving problems with this command:

**Comment by japerry911** [comment]
This command does appear to work fine when I install and use Prefect-GCP `v0.1.8` with nothing changed but the Prefect-GCP package:

```bash
prefect deployment build sky-pipe/flows/test_flow.py:test_flow -n testaroo -q sky-pipe --skip-upload -a -ib "cloud-run-job/test"
```

**Comment by anna-geller** [comment]
+1 also experienced the same issue now with the latest version of prefect-gcp 0.2.2 and Prefect 2.7.6

I think the SecretDict cannot be serialized to create a deployment YAML file

`TypeError: Object of type 'SecretDict' is not JSON serializable`

**Comment by ahuang11** [comment]
Thanks for adding additional info! #8074 should fix this.
