### ISSUE TITLE
name 'BigQueryClient' is not defined

### ISSUE THREAD

**Issue by timodechau** [PrefectHQ/prefect-gcp#22]
Installed via 'poetry add prefect_gcp'

Importing this:

from prefect import flow, task
from prefect_gcp import GcpCredentials
from prefect_gcp.cloud_storage import cloud_storage_upload_blob_from_file

the second line triggers this exception:

`Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from prefect_gcp import GcpCredentials
  File "/Users/timodechau/Library/Caches/pypoetry/virtualenvs/datafunctions-_z1_YbqT-py3.9/lib/python3.9/site-packages/prefect_gcp/__init__.py", line 2, in <module>
    from .credentials import GcpCredentials  # noqa
  File "/Users/timodechau/Library/Caches/pypoetry/virtualenvs/datafunctions-_z1_YbqT-py3.9/lib/python3.9/site-packages/prefect_gcp/credentials.py", line 62, in <module>
    class GcpCredentials:
  File "/Users/timodechau/Library/Caches/pypoetry/virtualenvs/datafunctions-_z1_YbqT-py3.9/lib/python3.9/site-packages/prefect_gcp/credentials.py", line 174, in GcpCredentials
    ) -> BigQueryClient:
NameError: name 'BigQueryClient' is not defined`

**Comment by ahuang11** [comment]
Thanks for reporting this! I think this was fixed in https://github.com/PrefectHQ/prefect-gcp/pull/18

@desertaxle should we make a new release for this fix?
