### ISSUE TITLE
Bug: trigger_dbt_cli_command for BigQuery target fails, if credentials are provided with service_account_info

### ISSUE THREAD

**Issue by andnig** [PrefectHQ/prefect-gcp#43]
I use the prefect-dbt package together with prefect-gcp to run dbt cli commands against BigQuery. 
The flow runs into an exception, if I use service_account_info instead of service_account_file in the GcpCredentials object. 

> **Note:** As the exception is about GcpCredentials, I opened the issue in this repository. If the issue however is related to prefect-dbt, let me know

# Steps to reproduce
1. Create a flow with trigger_dbt_cli_command and using BigQueryTargetConfigs as target. 
    ```python
    from prefect import flow, task, get_run_logger
    from prefect.task_runners import SequentialTaskRunner
    from prefect_gcp import GcpCredentials
    from logging import Logger
    from prefect_dbt.cli.credentials import DbtCliProfile
    from prefect_dbt.cli.commands import trigger_dbt_cli_command
    from prefect_dbt.cli.configs import BigQueryTargetConfigs
    import json
    
    def create_dbt_profile():
        credentials = GcpCredentials(
            service_account_info=json.dumps({
      "type": "ssss",
      "project_id": "ssss",
      "private_key_id": "ssss",
      "private_key": "sssss",
      "client_email": "ssss",
      "client_id": "sssss",
      "auth_uri": "ssssss",
      "token_uri": "sssssss",
      "auth_provider_x509_cert_url": "ssssss",
      "client_x509_cert_url": "ssssss"
    })
            # service_account_file = "/mypath/google_sa_keys/vn_at_vol_at_bigquery.json"
        )
    
        target_configs = BigQueryTargetConfigs(
            schema="dbt_anigg",
            project="ssss",
            credentials=credentials,
            location="EU",
            maximum_bytes_billed= 10000000000,
            type="bigquery",
            threads=8
        )
    
        dbt_cli_profile = DbtCliProfile(
            name="test",
            target="dev",
            target_configs=target_configs
        )
    
        return dbt_cli_profile
    
    # %%
    @flow(name="run_dbt_pipeline",
    description="Runs a dbt pipeline containing dbt test and dbt run for the specified selects",
    task_runner=SequentialTaskRunner, timeout_seconds=3600)
    def run_dbt_pipeline(should_test = True, should_run = True):
        """
        Runs a dbt pipeline containing dbt test and dbt run for the specified selects.
        The steps (test and run) can be selected or deselected via flow parameters.
        """
        logger = get_run_logger()
        dbt_cli_profile = create_dbt_profile()
    
        if should_test:
            result = trigger_dbt_cli_command(
                "dbt test",
                overwrite_profiles=True,
                dbt_cli_profile=dbt_cli_profile,
                profiles_dir="./",
                project_dir="/mydir"
            )
        return
    
    
    # %%
    if __name__ == "__main__":
        run_dbt_pipeline(should_test=True, should_run=False)

    ```
2. Run the flow

# Result
The flow runs into an exception. Summary:
```
pydantic.error_wrappers.ValidationError: 1 validation error for GcpCredentials
service_account_info
  JSON object must be str, bytes or bytearray (type=type_error.json)
```
Full Exception see at the bottom of this issue:

# Expected 
No exception

# Additional info
- it's the same outcome whether one json.dumps the service account dict or directly uses the dict
- If one uses the service_account_file parameter instead of service_account_info - everything works as expected!

# Full Exception
```
13:15:56.822 | ERROR   | Flow run 'enlightened-raptor' - Finished in state Failed('Flow run encountered an exception.')
Traceback (most recent call last):
  File "/home/andreas/github/datawarehouse/prefect/flows/dbt/dbt_flows.py", line 77, in <module>
    run_dbt_pipeline(should_test=True, should_run=False)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/flows.py", line 384, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/engine.py", line 156, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/client.py", line 104, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/engine.py", line 236, in create_then_begin_flow_run
    return state.result()
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/orion/schemas/states.py", line 145, in result
    raise data
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/engine.py", line 587, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 114, in run_sync_in_interruptible_worker_thread
    async with anyio.create_task_group() as tg:
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 96, in capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
  File "/home/andreas/github/datawarehouse/prefect/flows/dbt/dbt_flows.py", line 65, in run_dbt_pipeline
    result = trigger_dbt_cli_command(
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/tasks.py", line 294, in __call__
    return enter_task_run_engine(
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/engine.py", line 727, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 136, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/engine.py", line 859, in create_task_run_then_submit
    return await future._result()
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/futures.py", line 227, in _result
    return final_state.result(raise_on_failure=raise_on_failure)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/orion/schemas/states.py", line 145, in result
    raise data
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/task_runners.py", line 214, in submit
    result = await run_fn(**run_kwargs)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/engine.py", line 1000, in begin_task_run
    return await orchestrate_task_run(
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/engine.py", line 1065, in orchestrate_task_run
    resolved_parameters = await resolve_inputs(parameters)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/engine.py", line 1291, in resolve_inputs
    return await run_sync_in_worker_thread(
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 56, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/utilities/collections.py", line 300, in visit_collection
    items = [(visit_nested(k), visit_nested(v)) for k, v in expr.items()]
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/utilities/collections.py", line 300, in <listcomp>
    items = [(visit_nested(k), visit_nested(v)) for k, v in expr.items()]
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/utilities/collections.py", line 266, in visit_nested
    return visit_collection(
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/utilities/collections.py", line 313, in visit_collection
    items = [visit_nested(getattr(expr, key)) for key in model_fields]
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/utilities/collections.py", line 313, in <listcomp>
    items = [visit_nested(getattr(expr, key)) for key in model_fields]
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/utilities/collections.py", line 266, in visit_nested
    return visit_collection(
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/utilities/collections.py", line 313, in visit_collection
    items = [visit_nested(getattr(expr, key)) for key in model_fields]
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/utilities/collections.py", line 313, in <listcomp>
    items = [visit_nested(getattr(expr, key)) for key in model_fields]
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/utilities/collections.py", line 266, in visit_nested
    return visit_collection(
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/utilities/collections.py", line 323, in visit_collection
    model_instance = typ(
  File "/home/andreas/miniconda3/envs/prefect-dbt/lib/python3.10/site-packages/prefect/blocks/core.py", line 165, in __init__
    super().__init__(*args, **kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GcpCredentials
service_account_info
  JSON object must be str, bytes or bytearray (type=type_error.json)
```

**Comment by ahuang11** [comment]
Thanks for providing a detailed bug report with reproducible example. #44 should fix this!
